---
title: ソケットでbroken pipe
tags: Linux socket C++
author: dameyodamedame
slide: false
---
# 序

何かgoでそういう話の記事を読んだので思いつきで書いておきます。goの話はplatform固有ではありませんが、C/C++では標準ライブラリでsocketを扱えないので、今回はLinuxでのお話になります。

# broken pipeとソケット

## broken pipeとは

シグナルのSIGPIPEが送られるとこれになります。

### 自分で送るSIGPIPE
例えばこんな感じ…

```terminal
$ sleep 1d&
[1] 16495
$ 
```
バックグラウンドで一日sleepするプロセスを起動しました。このプロセスにSIGPIPEを送ってみます。
```terminal
$ kill -PIPE %1
$
```
無事送れました。再度エンターを押してみると、バックグラウンドプロセスの終了報告が出力されます。
```terminal
$
[1]+  Broken pipe             sleep 1d
$
```

出ましたね。これがBroken pipeです。ただ普通はこんな使い方をしません。

### パイプで発生するBroken pipe

pipeという名前から分かるとおり、パイプの出力先が突然いなくなったときに出力元のプロセスに対してOSから送られるシグナルになります。例えばこんなシェルスクリプトを用意したとしましょう。

```terminal
$ cat hoge.sh 
dd if=/dev/random bs=256 count=1 | hexdump -C
echo $? 1>&2
$ 
```
/dev/randomから256バイト読み込んでhexdumpで16進数出力するプログラムです。最後に`$?`で直前のコマンド(ここではhexdump)の終了コードを表示しています(`$?`を使ってもパイプの最後の終了コードしか知ることはできません)。

ちょっと実行するとこうなります。
```terminal
$ sh hoge.sh 
1+0 レコード入力
1+0 レコード出力
256 bytes copied, 0.000195802 s, 1.3 MB/s
00000000  42 00 a7 63 76 31 5b a2  a0 9a f9 07 d9 85 a0 13  |B..cv1[.........|
00000010  33 ce 63 21 fe c1 f0 12  e7 ad 43 f3 3d c9 3a 52  |3.c!......C.=.:R|
00000020  40 54 77 54 b3 82 ce d9  dc 3b 78 5c f8 25 aa d1  |@TwT.....;x\.%..|
00000030  49 88 42 af 52 85 9b be  17 30 89 7f 93 18 ea d4  |I.B.R....0......|
00000040  05 ce 63 5c bd 7c 23 53  bd f0 21 96 37 9f 3f 38  |..c\.|#S..!.7.?8|
00000050  ec 40 63 91 88 b0 6a 9b  63 87 80 59 03 f5 9a c6  |.@c...j.c..Y....|
00000060  57 c2 f6 15 57 69 bc 63  43 86 dc ec fb 65 83 4b  |W...Wi.cC....e.K|
00000070  72 65 1d 7d 9d df d4 53  23 e8 b6 2b 68 49 9e 15  |re.}...S#..+hI..|
00000080  df fc 6b e3 8e 5b b0 c4  21 56 cc 6a bb 0e f8 df  |..k..[..!V.j....|
00000090  51 12 ab 09 20 52 f6 cf  db 04 74 5c 02 81 d9 70  |Q... R....t\...p|
000000a0  a2 88 25 c5 66 56 1b 88  11 31 c4 42 3c f4 6f 03  |..%.fV...1.B<.o.|
000000b0  81 27 cc 00 bd 26 b1 46  c8 29 65 fa 46 5d fc 25  |.'...&.F.)e.F].%|
000000c0  98 86 31 69 b8 da 37 32  99 8a 60 af 76 ee 62 09  |..1i..72..`.v.b.|
000000d0  e9 f2 91 49 a2 91 c2 64  ad be cb 25 22 06 7f e9  |...I...d...%"...|
000000e0  3a da 1c 3b 43 01 e2 32  42 27 47 c4 cc 3c 79 13  |:..;C..2B'G..<y.|
000000f0  51 50 6d 20 57 a9 ca 96  d0 45 3c 02 60 eb 82 00  |QPm W....E<.`...|
00000100
0
$
```
最初の3行はddコマンドが標準エラー出力に出力したものです。ddコマンドは/dev/randomから256バイト読んで、そのまま標準出力に出力するので、それをパイプで標準入力から受け取ったhexdumpが16進ダンプ形式にして標準出力(画面)に出力しています。それがダンプデータです。
そして最後の0という出力がシェルスクリプト2行目で標準エラー出力に吐いたhexdumpの終了コードです。

では、このシェルスクリプトにパイプを付けてこうしたらどうなるでしょう？

```terminal
$ sh hoge.sh | /usr/bin/echo "hoge"
hoge
1+0 レコード入力
1+0 レコード出力
256 bytes copied, 0.000239643 s, 1.1 MB/s
141
$
```
/usr/bin/echoコマンドは標準入力から何も読み込みません。なのにパイプで繋いでいるので、hexdumpが出力した16進ダンプは全く読み込まれず、OSからSIGPIPEが送られます。なので、出力の最終行に141という数字が出ています。これはhexdumpコマンドの終了コードです。

あんまりいいリンクがなかったので恐縮ですが、コレですね。

https://www.baeldung.com/linux/status-codes#fatal-error-signal

> In Linux, programs might send one of 31 different standard signals. When a program terminates after receiving one of these signals, it returns an error code equal to 128 + signal-number. For example, when we terminate a program by using Ctrl+C, we effectively send it a SIGINT signal.

141 - 128 = 13 = SIGPIPE

例えばあなたのLinux環境でも

```terminal
$ find /usr/include -type f -name '*.h' | xargs grep 'SIGPIPE'
```

とかすればなんか色々13である証拠が出てくるはずです。

つまり、hexdumpはSIGPIPEを受け取ってBroken pipeで終了していたということです。

## ソケットでBroken pipeになる状況とは…

LinuxのようなU◯ixライクなOSでは、socketもファイルディスクリプタの一種として表します。なので、通信相手が切断されている状況で送信したりすると、そのプロセスにはSIGPIPEが送られて、何の準備もしてないとBroken pipeで異常終了しちゃったりするわけです。

まずは実験してみます。

### サーバーコード

```c++:server1.cpp
#include <iostream>
#include <stdexcept>
#include <cstring>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

struct s_socket {
    int sock;
    s_socket(int sock): sock(sock) {}
    s_socket(const s_socket&)=delete;
    s_socket& operator=(const s_socket&) = delete;
    operator int() {return this->sock;}
    ~s_socket() {if (this->sock != -1) close(this->sock);}
};

using namespace std;

int main() {
    try {
        s_socket sock = ::socket(AF_INET, SOCK_STREAM, 0);
        sockaddr_in addr, caddr;
        socklen_t len_caddr = sizeof(caddr);
        ::memset(&addr, 0, sizeof(addr));
        addr.sin_family = AF_INET;
        addr.sin_port = ::htons(8080);
        addr.sin_addr.s_addr = INADDR_ANY;
        if (::bind(sock, (struct sockaddr *)&addr, sizeof(addr)) != 0) throw runtime_error(::strerror(errno));
        if (::listen(sock, 5) != 0)  throw runtime_error(::strerror(errno));
        while (true) {
            s_socket con = ::accept(sock, (struct sockaddr *)&caddr, &len_caddr);
            if (con == -1)  throw runtime_error(::strerror(errno));
            cout << "accepted" << endl;
            ::shutdown(con, SHUT_RDWR);
            cout << "shutdown(SHUT_RDWR)" << endl;
        }
    }
    catch(runtime_error& e) {
        cerr << "catched: " << e.what() << endl;
    }
    return 0;
}
```

acceptしてすぐshutdownする何をしたいのか分からないコードです。まあ通例最初に送るのはクライアントなので、初手切断が一番速いのでこうしています。

### クライアントコード

```c++
#include <iostream>
#include <vector>
#include <cstring>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

struct s_socket {
    int sock;
    s_socket(int sock): sock(sock) {}
    s_socket(const s_socket&)=delete;
    s_socket& operator=(const s_socket&) = delete;
    operator int() {return this->sock;}
    ~s_socket() {if (this->sock != -1) close(this->sock);}
};

using namespace std;

int main() {
    try {
        s_socket con = socket( AF_INET, SOCK_STREAM, 0 );
        sockaddr_in addr;
        memset(&addr, 0, sizeof(addr));
        addr.sin_family = AF_INET;
        addr.sin_port = htons(8080);
        addr.sin_addr.s_addr = inet_addr("127.0.0.1");
        if (connect(con, (struct sockaddr *)&addr, sizeof(addr)) != 0) throw runtime_error(strerror(errno));
        ssize_t len = 0;
        vector<char> buff(4096);
        for (char offset = 0; offset < 3; ++offset) {
            buff[0] = 'a' + offset;
            len = write(con, &buff[0], 1);
            if (len <= 0) throw runtime_error(strerror(errno));
            cout << "write(): " << buff[0] << endl;
            sleep(5);
        }
        shutdown(con, SHUT_WR);
        cout << "shutdown(SHUT_WR)" << endl;
    }
    catch(runtime_error& e) {
        cerr << "catched: " << e.what() << endl;
    }
    return 0;
}
```
クライアントは`'a'`を送信して、`'b'`を送信して、`'c'`を送信してshutdownするコードです。各送信には5秒間の待ち時間があり、パケットが分かれるようになっています。

### 実行

各プログラムを同じLinux上の別端末で、サーバー→クライアントの順で起動します。結果は以下のとおりです。

```terminal: サーバー側
$ ./server1
accepted
shutdown(SHUT_RDWR)

```

```terminal: クライアント側
$ ./client1 
write(): a
$ echo $?
141
$
```

クライアント側は最初の送信をして5秒後に終了しています。例外をキャッチした形跡もなく、かといって正常終了もしていない、、、つまり落ちたということです。終了コードは141なのでBroken pipeですね。

ちなみにクライアントがいつ落ちているかというと、writeの前後にcout << ... << endlを挟んだり、デバッグ実行すればわかりますが、2回目のwriteの瞬間です。

### パケットの調査

一応実行したときのパケットの流れも簡単に追っておきます。tcpdumpを使うので入ってなかったら入れて下さい。

```terminal
$ sudo tcpdump -i lo port 8080
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on lo, link-type EN10MB (Ethernet), snapshot length 262144 bytes
00:12:07.997230 IP localhost.52742 > localhost.http-alt: Flags [S], seq 2073251709, win 65495, options [mss 65495,sackOK,TS val 2232722591 ecr 0,nop,wscale 7], length 0
00:12:07.997246 IP localhost.http-alt > localhost.52742: Flags [S.], seq 2329054288, ack 2073251710, win 65483, options [mss 65495,sackOK,TS val 2232722591 ecr 2232722591,nop,wscale 7], length 0
00:12:07.997260 IP localhost.52742 > localhost.http-alt: Flags [.], ack 1, win 512, options [nop,nop,TS val 2232722591 ecr 2232722591], length 0
00:12:07.997301 IP localhost.52742 > localhost.http-alt: Flags [P.], seq 1:2, ack 1, win 512, options [nop,nop,TS val 2232722591 ecr 2232722591], length 1: HTTP
00:12:07.997307 IP localhost.http-alt > localhost.52742: Flags [.], ack 2, win 512, options [nop,nop,TS val 2232722591 ecr 2232722591], length 0
00:12:07.997469 IP localhost.http-alt > localhost.52742: Flags [F.], seq 1, ack 2, win 512, options [nop,nop,TS val 2232722592 ecr 2232722591], length 0
00:12:07.997505 IP localhost.http-alt > localhost.52742: Flags [R.], seq 2, ack 2, win 512, options [nop,nop,TS val 2232722592 ecr 2232722591], length 0
```

最初の3行は3Wayハンドシェイクなので無視、4～5行目が最初のwrite()とそのackです。最初のwrite()はもうハンドシェイクの最後にくっついて送られているようなもので、サーバー側ではacceptしたときには既に受け取っていたのでしょう。そのため、shutdownが実行される前にもうTCPスタックでackを送ってしまっています。サーバーアプリ側でacceptした後すぐshutdownしても、すでにデータを受け取ってしまっているので、FINに続いてRSTも出している感じになっています。

クライアント側では多分write()の後sleepしてる頃には余裕でRSTが届いているのですが、TCPスタック側は非同期シグナルで起こすような真似をせず、クライアント側がreadさえしてくれたらFINの処理でEOFを渡してRSTは捨ててくれようとしているわけです。しかし空気の読めないクライアントが再びwrite()をしたため、目出度くSIGPIPEでお叱りを受けたということのようです。なおSIGPIPEの定義上はRSTはあまり関係ないように見えますが、FINだけではSIGPIPEは発生しません(sleepの位置を前にずらしてFINが届いている状態でwriteしてもSIGPIPEがはっせいしない)。

### これ受信だけshutdownしたらどうなるの？

勘の良い人ならそう思うかも知れません。shutdownはcloseと違い、送信/受信別々に出来ます。受信が閉じられてるならBroken pipeになるのでは？と。

```diff_cpp
--- server1.cpp 2024-08-09 00:28:03.200436951 +0900
+++ server2.cpp 2024-08-09 00:38:48.726104209 +0900
@@ -33,8 +33,9 @@ int main() {
             s_socket con = ::accept(sock, (struct sockaddr *)&caddr, &len_caddr);
             if (con == -1)  throw runtime_error(::strerror(errno));
             cout << "accepted" << endl;
-            ::shutdown(con, SHUT_RDWR);
-            cout << "shutdown(SHUT_RDWR)" << endl;
+            ::shutdown(con, SHUT_RD);
+            cout << "shutdown(SHUT_RD)" << endl;
+            sleep(24 * 60 * 60);
         }
     }
     catch(runtime_error& e) {
```

最後sleepしてるのは、そのまま終わるとconのデストラクタでcloseされちゃうからです。

では実行してみましょう。

```terminal:サーバー側
$ ./server2
accepted
shutdown(SHUT_RD)

```
```terminal:クライアント側
$ ./client1 
write(): a
write(): b
write(): c
shutdown(SHUT_WR)
$ echo $?
0
$ 
```

はい、Broken pipeになりません。クライアント側は正常に終了してしまっています。shutdown(fd,SHUT_RD)はローカルなアクションで、通信相手には伝わらないからです。shutdown(fd,SHUT_WR)がFINのトリガで、原則それ以降でRSTが起こります。パケットもキャプチャすればFINもRSTも出ていないことが分かります(ここでは省略)。

なお、SHUT_WRの後も普通にreadが出来るし、大抵のプロトコルはそれを期待しています。そして先にSHUT_WRをした方がTIME_WAITになり余計なリソースを使うので、通常クライアント側からSHUT_WRを行うのが一般的です。つまり普通のプロトコルでは、サーバー側から先にclose/shutdownするシナリオは異常系だけということです。今回サーバー側で強引なshutdownをしているのは、真面目に書くと複雑になりがちなサーバー側実装でbroken pipeの調査をするのは説明が面倒だったからです。ただし落ちて困るのは比較的サーバー側なので、本来はサーバーの方がよりbroken pipeを気にします。

### でもSIGPIPEって誰が受け取るの？

落ちるのはSIGPIPEを全く処理していないからなのですが、これを使うと何が出来るのでしょうか？そもそも複数のスレッドがあるとき、誰が受け取るのでしょう？

例えばサーバーであれば、複数のクライアントと同時に通信しているわけで、そのいずれかでRSTを受け取った場合、どのスレッドがSIGPIPEを拾うことになるのか？という意味です。つまり、SIGPIPEを引き起こしてしまったwrite/sendを呼び出したスレッドでなければ意味がないということです。

では調べてみましょう。

```cpp:client2.cpp
#include <iostream>
#include <vector>
#include <thread>
#include <cstring>
#include <csignal>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

struct s_socket {
    int sock;
    s_socket(int sock): sock(sock) {}
    s_socket(const s_socket&)=delete;
    s_socket& operator=(const s_socket&) = delete;
    operator int() {return this->sock;}
    ~s_socket() {if (this->sock != -1) close(this->sock);}
};

using namespace std;

#define PRINT_N(N) {\
    auto num = N; \
    char ch[10] = {0,0,0,0,0,0,0,0,0,0}; \
    char* p = &ch[9]; \
    while (num != 0) { \
        *p-- = '0' + num % 10; \
        num /= 10; \
    } \
    ++p; \
    write(1, p, size(ch) - (p-&ch[0])); \
}

void callback(int sig) { // シグナル割り込み中なので、スタックを気にして関数化しないし、最低限のシグナル安全なシステムコールしか使わない
    write(1, "interrupted: ", 13);
    PRINT_N(sig)
    write(1, "\n", 1);
    write(1, "thread id: ", 11);
    uint32_t tid = gettid();
    PRINT_N(tid);
    write(1, "\n", 1);
}

int main() {
    cout << "mainthread id: " << gettid() << endl;
    struct sigaction sa;
    sa.sa_handler = callback;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    if (sigaction(SIGPIPE, &sa, NULL) != 0) {
        perror("sigaction");
        exit(1);
    }
    thread t([]{
        try {
            cout << "socket thread id: " << gettid() << endl;
            s_socket con = socket( AF_INET, SOCK_STREAM, 0 );
            sockaddr_in addr;
            memset(&addr, 0, sizeof(addr));
            addr.sin_family = AF_INET;
            addr.sin_port = htons(8080);
            addr.sin_addr.s_addr = inet_addr("127.0.0.1");
            if (connect(con, (struct sockaddr *)&addr, sizeof(addr)) != 0) throw runtime_error(strerror(errno));
            ssize_t len = 0;
            vector<char> buff(4096);
            for (char offset = 0; offset < 3; ++offset) {
                buff[0] = 'a' + offset;
                len = write(con, &buff[0], 1);
                if (len <= 0) throw runtime_error(strerror(errno));
                cout << "write(): " << buff[0] << endl;
                sleep(5);
            }
            shutdown(con, SHUT_WR);
            cout << "shutdown(SHUT_WR)" << endl;
        }
        catch(runtime_error& e) {
            cerr << "catched: " << e.what() << endl;
        }
    });
    t.join();
    return 0;
}
```
[^1]
メインスレッドと区別するために処理を起動したスレッド中に移しています。また、SIGPIPEのシグナルハンドラを書いて、スレッドIDを出力させてみました。

実行した結果がこちらです。

```terminal:サーバー側
$ ./server1
accepted
shutdown(SHUT_RDWR)

```

```terminal:クライアント側
$ ./client2
mainthread id: 19051
socket thread id: 19052
write(): a
interrupted: 13
thread id: 19052
catched: Broken pipe
$ echo $?
0
$
```

どうやらちゃんとソケットにwrite()したスレッドから呼ばれているようです。ただし、この動作はLinux固有かもしれませんし、必ずそうなるのか？というと自信がありません。

そしてシグナルで落ちなくなった結果、処理が次に進み、writeがエラーを返しています。エラーはEPIPEです。例外を作ってthrowするコードにしているのでそれがキャッチされて正しく処理され、正常終了しています。

### SIGPIPEシグナルハンドラは必要なのか？

調べた限りではシグナルハンドラで頑張ろうとする資料は皆無でした。特にリモートなSIGPIPEだと、非同期に送られるシグナルではなく、自ら能動的に処理した結果発生する同期的なシグナル(今回だと書き込み/送信という能動的なアクションの結果として発生しており、外部から非同期に呼ばれるわけではない)なので、非同期を前提としたシグナルでなくとも、単純に処理の結果としてエラーが返ればいいのでは？という発想のアプローチが多かったです。つまり要らなそうということですね。

### じゃあSIGPIPEはどうすればいいの？

全会一致レベルで答えは「無視する」でした。無視してもちゃんとエラーが返ります。無視しなくてもさっきはエラーEPIPEが検出されてましたよね。無視してもちゃんと返るのです。では実装してみます。

```diff_cpp
--- client1.cpp 2024-08-09 00:11:13.213117586 +0900
+++ client3.cpp 2024-08-09 00:12:01.576955593 +0900
@@ -1,6 +1,7 @@
 #include <iostream>
 #include <vector>
 #include <cstring>
+#include <csignal>
 #include <unistd.h>
 #include <sys/types.h>
 #include <sys/socket.h>
@@ -20,6 +21,15 @@ using namespace std;
 
 int main() {
     try {
+        struct sigaction sa;
+        sa.sa_handler = SIG_IGN;
+        sigemptyset(&sa.sa_mask);
+        sa.sa_flags = 0;
+        if (sigaction(SIGPIPE, &sa, NULL) != 0) {
+            perror("sigaction");
+            exit(1);
+        }
+
         s_socket con = socket( AF_INET, SOCK_STREAM, 0 );
         sockaddr_in addr;
         memset(&addr, 0, sizeof(addr));
```
シグナルハンドラ部分をSIG_IGNにしただけですね。
実行してみます。

```terminal:サーバー側
$ ./server1
accepted
shutdown(SHUT_RDWR)

```
```terminal:クライアント側
$ ./client3
write(): a
catched: Broken pipe
$ echo $?
0
$
```
同じですね。POSIX標準機能なので良いのですが、ただ、これはプロセス全体でSIGPIPEを無視してしまう方法です。socket周りでは無視で良くても他では使いたいというケースもあるかもしれません。Linuxでは別の方法でも無視する事ができます。

```diff_cpp
--- client1.cpp 2024-08-09 00:11:13.213117586 +0900
+++ client4.cpp 2024-08-09 00:22:13.544174759 +0900
@@ -31,7 +31,7 @@ int main() {
         vector<char> buff(4096);
         for (char offset = 0; offset < 3; ++offset) {
             buff[0] = 'a' + offset;
-            len = write(con, &buff[0], 1);
+            len = send(con, &buff[0], 1, MSG_NOSIGNAL);
             if (len <= 0) throw runtime_error(strerror(errno));
             cout << "write(): " << buff[0] << endl;
             sleep(5);
```

writeではなく、sendシステムコールを使用し、MSG_NOSIGNALを付ける、という方法です。実行するとさっきと同じ結果になります。

なお、Linuxではこういうアプローチですが、他のU◯ixライクなOSだと
```c
int flag = 1;
setsockopt(sock, SOL_SOCKET, SO_NOSIGPIPE, (void *)&flag, sizeof(int));
```
みたいにソケットのオプション設定にSO_NOSIGPIPEを付ける、という手段を用意しているようです。

# まとめ

- ソケット通信で切断された接続に書き込むとSIGPIPEで落ちる
- SIGPIPEをSIG_IGNにすればwrite/sendでEPIPEを拾うことが出来る
- LinuxではsendにMSG_NOSIGNALを付けても無視できる

# おまけ

ついでにgoも同じことをしてみました。

```go:server.go
package main

import (
    "os"
    "log"
    "net"
)

func main() {
    listener, err := net.Listen("tcp", ":8080")
    if err != nil {
        log.Fatal(err)
    }
    defer listener.Close()
    conn, err := listener.Accept()
    if err != nil {
        log.Fatal("Server Accept", err)
        os.Exit(1)
    }
    log.Println("Server: Accepted one connection")
    conn.Close()
    log.Printf("Server: Closing\n")
}
```
```go:client.go
package main

import (
    "log"
    "net"
    "time"
)

func main() {
    con, err := net.Dial("tcp", "localhost:8080")
    if err != nil {
        log.Fatal("Client Dial", err)
    }
    defer con.Close()
    log.Println("Client:", time.Now(), "writes 1st byte 'a' to server")
    if _, err := con.Write([]byte("a")); err != nil {
        log.Fatal("Client Write", err)
    }
    time.Sleep(5 * time.Second)
    log.Println("Client:", time.Now(), "writes 2nd byte 'b' to server")
    if _, err := con.Write([]byte("b")); err != nil {
        log.Fatal("Client Write", err)
    }
    time.Sleep(5 * time.Second)
    log.Println("Client:", time.Now(), "writes 3rd byte 'c' to server")
    if _, err := con.Write([]byte("c")); err != nil {
        log.Fatal("Client Write", err)
    }
}
```
```terminal:サーバー側
$ go run server.go 
2024/08/09 11:33:52 Server: Accepted one connection
2024/08/09 11:33:52 Server: Closing
$ 
```
```terminal:クライアント側
$ go run client.go 
2024/08/09 11:33:52 Client: 2024-08-09 11:33:52.71268338 +0000 UTC m=+0.000861657 writes 1st byte 'a' to server
2024/08/09 11:33:57 Client: 2024-08-09 11:33:57.716421188 +0000 UTC m=+5.004599515 writes 2nd byte 'b' to server
2024/08/09 11:33:57 Client Writewrite tcp [::1]:46788->[::1]:8080: write: broken pipe
exit status 1
$ 
```
SIGPIPEはランタイム側で処理/無視されているようですね。

[^1]: コード上スタックがキツキツみたいなこと書いてますが、今調べたらそれはなさそうです。
https://www.win.tue.nl/~aeb/linux/lk/lk-5.html#ss5.6

